# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  apt_packages:
    - swig

mkdocs:
  configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - method: pip
      path: .
