# .readthedocs.yaml
# Read the Docs configuration file

# Required
version: 2

# Set the version of Python
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - echo "$HOME/.local/bin" >> $GITHUB_PATH || true
      - $HOME/.local/bin/uv pip install .[docs]

mkdocs:
  configuration: mkdocs.yaml
