name: qdaxpy38
channels:
- defaults
- conda-forge
dependencies:
- python=3.8
- pip>=20.3.3
- conda>=4.9.2
- pip:
    - --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
    - jaxlib==0.3.15
    - -r requirements.txt
    - -r requirements-dev.txt
